[dev]
  framework = "#static"

[build]
  command = "echo No build for this site, we are living on the edge"
  publish = "public"

[context.production]
  environment = { MY_IMPORTANT_VARIABLE = "this is a very important secret" }

[[edge_functions]]
  path = "/paths/*"
  excludedPath = "/paths/excluded/*"
  function = "test-excluded-path"
